# Construindo um ambiente PHP
services:
  # image / container php:7.4-fpm
  php:
    build:
      context: .
    image: phpenvironment
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html"
    command: php -S 0.0.0.0:9000 -t public/
    links: 
      - mysql
  # image / container mariadb:10.11
  mysql:
    image: mariadb:10.11
    container_name: mariadb_dkr
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
volumes:
  mysql: 