# Construindo um ambiente PHP
services:
  # image / container nginx
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - mariadb
  # image / container php:7.4-fpm
  php:
    build:
      context: .
    image: php_environment
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html"
    # command: php -S 0.0.0.0:9000 -t public/
    # links: 
    #  - mysql
  # image / container mariadb:10.11
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_dkr
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
volumes:
  mysql: 